### ISSUE TITLE
user.getTopTags is documented inaccurately

### ISSUE THREAD

**Issue by PvtTyphoon** [lastfm-docs/api-docs#12]
user.getTopTags seems to have most of its content copied over from ~user.getTopArtists, the description as well as the main body reflect this

**Comment by PvtTyphoon** [comment]
@Aidan0000 can you review this please

**Comment by Aidan0000** [comment]
I've amended the description as well as added a warning about status codes, what bit of the main body were you referring to?

**Comment by PvtTyphoon** [comment]
nope looks like you've fixed everything, I meant the second part of the description by body, about the time periods and stuff 

thanks :D
